---
title: "Codebook for Getting Data Course Project"
author: "maggierui"
date: "Oct 23, 2015"
output:
  featuremean.txt:
    keep_md: yes
---

## Project Description
Coursera Data Science Specialization series - Getting Data Course project 
##Study design and data processing
Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

The data was obtained from following link: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

###Collection of the raw data
Following description about the data collection process was retrieved here: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

###Notes on the original (raw) data 
The zip file "mobile.zip" is compressed from a folder named "UCI HAR Dataset". Inside of the folder, the following files can be found: 
- 'README.txt': explains each file's purpose. 
- 'features_info.txt': Shows information about the variables used on the feature vector.
- 'features.txt': List of all features. This is actually the list of variable names for the actual datasets, which are included in the "test" and "train" folders, named 'test/X_test.txt'and 'train/X_train.txt'
- 'activity_labels.txt': Links the class labels with their activity name.
- 'train/X_train.txt': Training set.
- 'train/y_train.txt': Training labels -- if the activity is one of the six: 
  1 WALKING
  2 WALKING_UPSTAIRS
  3 WALKING_DOWNSTAIRS
  4 SITTING
  5 STANDING
  6 LAYING
- 'test/X_test.txt': Test set.
- 'test/y_test.txt': Test labels if the activity is one of the six: 
  1 WALKING
  2 WALKING_UPSTAIRS
  3 WALKING_DOWNSTAIRS
  4 SITTING
  5 STANDING
  6 LAYING

##Creating the tidy datafile
The ultimate goals of this course project is to:
1.Merges the training and the test sets to create one data set.
2.Extracts only the measurements on the mean and standard deviation for each measurement. 
3.Uses descriptive activity names to name the activities in the data set
4.Appropriately labels the data set with descriptive variable names. 
5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

###Guide to create the tidy data file
To achieve the goals, follow these steps:
1. Download the data 
2. Unzip the data 
3. Read data sets 
4. Read data variable names
5. Give dat column names with varaibles names 
6. Subset only columns for means and standard deviations
7. Read in activity labels 
8.Rename the activity labels as "Activity"
9. Relabel activities into WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS...
10. Read in subject IDs 
11. Rename subject IDs to "ID" 
12. Combine subject ID, activity type, and actual dataset
13. Change variables names to more descriptive format by getting rid of punctuations; changing all upper case to lower cases, and some words replacement.
14. Calculate means by id and activities
19. Write the new data set to a txt file named "feature_means.txt"

##Description of the variables in the feature_means.txt file
This new independent tidy data set contains 180 rows and 68 variables.
The first column is "id", which means the subject ID, ranging from 1 to 30. 
The second column is "activity", which is one of the six type of activities mentioned above. 
The rest 66 variables are the means of each feature observed in the previous data set, by each subject for each type of activity.
##Note: there are many threads on the discussion forum about "to what level is descriptive". 
##      I choose to follow the "all lower case" and "no special character" rules.
##      Meanwhile, I decide not to replace every abrrevated words to their full versions, for the sake of readability.

Detailed description for each variable as shown below:
$ id                          : int  1 1 1 1 1 1 2 2 2 2 ...
 $ activity                    : chr  "LAYING" "SITTING" "STANDING" "WALKING" ...
 $ timebodyaccmeanx            : num  0.222 0.261 0.279 0.277 0.289 ...
 $ timebodyaccmeany            : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ timebodyaccmeanz            : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ timebodyaccstdx             : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ timebodyaccstdy             : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ timebodyaccstdz             : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ timegravityaccmeanx         : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ timegravityaccmeany         : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ timegravityaccmeanz         : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ timegravityaccstdx          : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ timegravityaccstdy          : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ timegravityaccstdz          : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ timebodyaccjerkmeanx        : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ timebodyaccjerkmeany        : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ timebodyaccjerkmeanz        : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ timebodyaccjerkstdx         : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ timebodyaccjerkstdy         : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ timebodyaccjerkstdz         : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ timebodygyromeanx           : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ timebodygyromeany           : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ timebodygyromeanz           : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ timebodygyrostdx            : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ timebodygyrostdy            : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ timebodygyrostdz            : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ timebodygyrojerkmeanx       : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ timebodygyrojerkmeany       : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ timebodygyrojerkmeanz       : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ timebodygyrojerkstdx        : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ timebodygyrojerkstdy        : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ timebodygyrojerkstdz        : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ timebodyaccmagmean          : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ timebodyaccmagstd           : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ timegravityaccmagmean       : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ timegravityaccmagstd        : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ timebodyaccjerkmagmean      : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ timebodyaccjerkmagstd       : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ timebodygyromagmean         : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ timebodygyromagstd          : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ timebodygyrojerkmagmean     : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ timebodygyrojerkmagstd      : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ frequencybodyaccmeanx       : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ frequencybodyaccmeany       : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ frequencybodyaccmeanz       : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ frequencybodyaccstdx        : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ frequencybodyaccstdy        : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ frequencybodyaccstdz        : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ frequencybodyaccjerkmeanx   : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ frequencybodyaccjerkmeany   : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ frequencybodyaccjerkmeanz   : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ frequencybodyaccjerkstdx    : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ frequencybodyaccjerkstdy    : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ frequencybodyaccjerkstdz    : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ frequencybodygyromeanx      : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ frequencybodygyromeany      : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ frequencybodygyromeanz      : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ frequencybodygyrostdx       : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ frequencybodygyrostdy       : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ frequencybodygyrostdz       : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ frequencybodyaccmagmean     : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ frequencybodyaccmagstd      : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ frequencybodyaccjerkmagmean : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
 $ frequencybodyaccjerkmagstd  : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ frequencybodygyromagmean    : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ frequencybodygyromagstd     : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ frequencybodygyrojerkmagmean: num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ frequencybodygyrojerkmagstd : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...


